// Texto autoral organizado pela interseção dos programas oficiais de SP (2025), GO (2025) e CE (2026).
const editalSources = [
  {name:'SEFAZ-SP · edital 02/2025', url:'https://portal.fazenda.sp.gov.br/servicos/concursos/Documents/EDITAL%20N%C2%BA%2002_2025%20-%20EDITAL%20DE%20ABERTURA%20DAS%20INSCRI%C3%87%C3%95ES.pdf'},
  {name:'Economia-GO · edital 2025', url:'https://goias.gov.br/economia/wp-content/uploads/sites/45/2025/05/EDITAL_Concurso_Aud_Sec_Economia_GO.pdf'},
  {name:'SEFAZ-CE · edital 2026', url:'https://www.ce.gov.br/sefaz/wp-content/uploads/sites/46/2026/04/do20260424p02.pdf'}
];
const studyGuide = {
  portugues: {
    overlap:'Núcleo comum nos três editais',
    sections:[
      ['Como ler a questão de interpretação', 'Comece pelo comando: a banca pede uma informação literal, uma inferência ou a intenção do autor? Marque no texto a tese central e os conectivos que articulam os argumentos. “Entretanto” indica oposição; “portanto” introduz conclusão; “porque” costuma introduzir causa ou explicação. Uma alternativa pode usar palavras verdadeiras isoladamente e, ainda assim, distorcer a relação entre elas. Para testar uma inferência, procure a passagem que a sustenta. Se não houver apoio textual, a alternativa extrapola.', 'Exemplo resolvido: “A arrecadação cresceu, embora a atividade econômica tenha recuado.” A oração com “embora” admite o recuo como fato e apresenta uma quebra de expectativa. Não conclua que o recuo causou o crescimento. A resposta correta descreve concessão, não causa.'],
      ['Sintaxe aplicada à reescrita', 'Localize o verbo e pergunte quem pratica ou sofre o processo para identificar o sujeito. Depois examine os complementos exigidos pelo verbo. Em “o auditor informou o contribuinte da decisão”, há objeto direto (“o contribuinte”) e complemento preposicionado (“da decisão”). Ao trocar um verbo, confira se a regência permite manter as preposições. Na concordância, observe o núcleo do sujeito, não a palavra mais próxima do verbo. Na crase, verifique duas condições: a regência pede preposição “a” e o termo seguinte aceita artigo feminino “a”.', 'Exemplo resolvido: “O relatório se refere à auditoria.” O verbo “referir-se” pede “a”; “auditoria” admite artigo “a”. A fusão produz “à”. Em “refere-se a processos”, não há artigo feminino singular, logo não há crase.'],
      ['Pontuação e sentido', 'A vírgula de uma oração explicativa acrescenta comentário sobre todo o referente; sem vírgulas, uma oração restritiva seleciona parte do conjunto. “Os contribuintes, que entregaram a declaração, receberam aviso” sugere que todos entregaram. “Os contribuintes que entregaram a declaração receberam aviso” restringe o grupo. A pontuação também marca vocativo e termos deslocados. Antes de aceitar uma reescrita, compare a informação preservada, a relação lógica e a correção gramatical.'],
      ['Treino orientado', 'Reescreva uma frase curta trocando “embora” por “apesar de” e confira se preservou a concessão. Em seguida, identifique sujeito, verbo e complementos. Resolva a questão sem olhar as alternativas; só depois procure a opção equivalente. Esse procedimento reduz o efeito de distrações que parecem familiares.']
    ]
  },
  logica: {
    overlap:'Núcleo comum nos três editais; matemática financeira e estatística também aparecem',
    sections:[
      ['Lógica proposicional', 'Uma proposição é uma afirmação que pode ser verdadeira ou falsa. A conjunção P ∧ Q só é verdadeira quando ambas são verdadeiras. A disjunção inclusiva P ∨ Q é falsa apenas quando ambas são falsas. A condicional P → Q é falsa quando P ocorre e Q não ocorre. Não confunda a linguagem cotidiana de “se” com causalidade: em lógica, a tabela-verdade define a relação. Para negar uma frase quantificada, troque “todo” por “existe ao menos um que não” e “existe” por “nenhum”.', 'Exemplo resolvido: “Todos os processos foram conferidos” é falsa se existir um único processo não conferido. A negação correta é “Ao menos um processo não foi conferido”; “Nenhum foi conferido” é forte demais.'],
      ['Matemática financeira', 'Juros simples seguem M = C(1 + in), com taxa i e períodos n na mesma unidade. Juros compostos seguem M = C(1 + i)^n, pois cada período incide sobre o saldo anterior. Uma taxa de 2% ao mês por dois meses produz fator composto 1,02² = 1,0404, ou 4,04% acumulados. Taxas sucessivas nunca devem ser somadas automaticamente. Uma taxa nominal anual com capitalização mensal exige identificar a taxa por período antes de aplicar a fórmula.'],
      ['Porcentagem, conjuntos e probabilidade', 'Um aumento de 25% seguido de desconto de 20% retorna ao valor inicial: 1,25 × 0,80 = 1. Em conjuntos, n(A ∪ B) = n(A) + n(B) − n(A ∩ B). Em probabilidade, defina primeiro o espaço amostral e verifique se os resultados são equiprováveis. Para eventos independentes, P(A ∩ B) = P(A)P(B); para eventos mutuamente exclusivos, a interseção é vazia. Independência e exclusão são ideias distintas.'],
      ['Treino orientado', 'Se um capital de R$ 1.000 rende 10% ao ano em regime composto, após dois anos vale R$ 1.210: 1.000 × 1,1². Se A tem 18 itens, B tem 12 e 5 estão em ambos, a união tem 25. Escreva a fórmula antes de substituir números e confira a unidade da resposta.']
    ]
  },
  informatica: {
    overlap:'Complementar; tecnologia e dados variam conforme a área do cargo',
    sections:[
      ['Planilhas para fiscalização', 'Trate cada linha como registro e cada coluna como variável. Antes de ordenar, selecione a tabela inteira; ordenar uma coluna isolada pode deslocar valores e corromper a associação entre nota, contribuinte e data. Filtros apenas ocultam linhas da visualização. Uma referência relativa como A1 muda quando a fórmula é copiada. Em $A$1, coluna e linha ficam fixas. Essa diferença é útil para multiplicar várias bases pela mesma taxa guardada em uma célula.'],
      ['Qualidade e segurança dos dados', 'Uma base fiscal exige validação de identificadores, datas, duplicatas e campos vazios. Uma soma correta sobre registros duplicados continua produzindo conclusão errada. Defina a chave de cada registro e documente a origem. HTTPS protege dados em trânsito, mas não garante a honestidade da página. Para contas administrativas, use autenticação multifator e permissões mínimas. Cópia de segurança só é confiável quando a restauração foi testada.'],
      ['Exemplo resolvido', 'Uma tabela traz três notas de R$ 100, R$ 200 e R$ 200. O terceiro registro tem a mesma chave da segunda nota. A soma direta é R$ 500; após deduplicar pela chave correta, é R$ 300. A decisão analítica depende da qualidade da base, não apenas da fórmula.']
    ]
  },
  constitucional: {
    overlap:'Núcleo comum nos três editais',
    sections:[
      ['Estrutura constitucional', 'A Constituição organiza o Estado, distribui competências e protege direitos. Sua supremacia significa que leis e atos infraconstitucionais devem ser compatíveis com ela. Normas constitucionais podem ter graus diferentes de aplicabilidade, mas nenhuma lei ordinária pode afastar uma regra constitucional válida. Para questões fiscais, concentre-se na federação, Administração Pública, fiscalização e sistema tributário constitucional.'],
      ['Federação e competências', 'União, estados, Distrito Federal e municípios são entes autônomos. Autonomia inclui competências legislativas, administrativas e tributárias dentro da repartição constitucional. Não confunda competência para instituir tributo com capacidade de fiscalizar ou arrecadar em determinada cooperação. Quando a questão tratar de ICMS, identifique a regra constitucional antes de ir ao regulamento estadual. Quando tratar de ISS, o imposto é municipal, embora possa haver controvérsia sobre a natureza da operação.'],
      ['Controle de constitucionalidade', 'No controle difuso, a compatibilidade de uma norma com a Constituição é examinada no contexto de um caso concreto. No concentrado, ações específicas discutem a validade da norma em tese perante o órgão competente. Controle preventivo ocorre antes do ingresso definitivo da norma no ordenamento; repressivo incide sobre norma já formada. Em prova, uma frase como “todo controle judicial é concentrado” está errada, pois há controle judicial difuso.'],
      ['Administração e direitos', 'O art. 37 apresenta legalidade, impessoalidade, moralidade, publicidade e eficiência. Legalidade administrativa exige atuação dentro do ordenamento; publicidade favorece controle e transparência, com restrições legítimas de sigilo quando cabíveis. Exemplo: uma seleção pública não pode favorecer pessoa determinada sob aparência de regra geral, pois viola impessoalidade. Para estudar, associe cada princípio a um caso concreto.']
    ]
  },
  administrativo: {
    overlap:'Núcleo comum nos três editais',
    sections:[
      ['Atos administrativos', 'Use a sequência competência, finalidade, forma, motivo e objeto para analisar validade. Competência é a atribuição legal do agente; finalidade é o interesse público previsto; motivo são pressupostos de fato e de direito; objeto é o efeito do ato. Um ato ilegal deve ser anulado. Um ato válido pode ser revogado por conveniência e oportunidade quando houver espaço legal, respeitados direitos e limites. Convalidação não corrige qualquer vício; depende de possibilidade jurídica e ausência de prejuízo indevido.'],
      ['Poderes e polícia administrativa', 'Poder hierárquico organiza a atuação interna; poder disciplinar permite apurar e sancionar infrações no vínculo jurídico correspondente; poder regulamentar detalha a execução da lei sem criar obrigação incompatível com ela. O poder de polícia condiciona direitos e atividades para proteger interesses públicos. Uma fiscalização de estabelecimento deve observar competência, procedimento e proporcionalidade. A existência de interesse público não dispensa base legal.'],
      ['Licitações e contratos', 'A Lei 14.133/2021 estrutura planejamento, seleção do fornecedor e execução contratual. A contratação direta, quando permitida, também exige processo e justificativa; dispensa não significa ausência de controles. Em questão, identifique se o enunciado trata de inexigibilidade, em que a competição é inviável, ou de dispensa, em que a lei autoriza contratar sem licitar em hipóteses específicas. Consulte a norma vigente para limites e prazos.'],
      ['Caso resolvido', 'Um órgão descobre que uma licença foi concedida por agente sem competência legal. O problema é de validade: a providência discutida é anulação ou eventual convalidação, se o vício for sanável. Se a licença era válida, mas uma política pública posterior mudou, analise se há possibilidade de revogação e quais direitos precisam ser respeitados. A palavra “ilegal” no enunciado costuma afastar a resposta “revogação”.']
    ]
  },
  tributario: {
    overlap:'Núcleo central nos três editais',
    sections:[
      ['Tributo e competência', 'O CTN define tributo como prestação pecuniária compulsória instituída em lei, que não constitui sanção de ato ilícito e é cobrada mediante atividade administrativa vinculada. Uma multa é sanção e, por isso, não se confunde com tributo. A Constituição distribui competências para instituir impostos; a atribuição não é alterada por simples acordo entre entes. Separe competência tributária, que é poder de criar o tributo, de capacidade ativa, ligada às funções de cobrança e fiscalização.'],
      ['Limitações ao poder de tributar', 'A legalidade impede, como regra, criação ou aumento de tributo sem lei. Irretroatividade protege fatos geradores anteriores à vigência da lei onerosa. Anterioridade posterga a cobrança em hipóteses constitucionais, com exceções que devem ser estudadas na norma. A imunidade retira competência para tributar determinada situação por comando constitucional. Isenção ocorre quando a própria legislação dispensa o pagamento de tributo em hipótese que, de outro modo, estaria no campo de incidência.'],
      ['Obrigação, lançamento e crédito', 'O fato gerador faz nascer a obrigação principal, cujo objeto é pagar tributo ou penalidade pecuniária. Obrigações acessórias envolvem deveres instrumentais, como prestar informações ou emitir documentos. O lançamento é procedimento administrativo de constituição do crédito tributário; não é sinônimo de pagamento. O CTN distingue suspensão da exigibilidade, extinção e exclusão do crédito. Moratória e parcelamento são exemplos de suspensão; pagamento é exemplo de extinção; isenção relaciona-se à exclusão.'],
      ['Caso resolvido', 'Uma empresa realiza operação tributada em janeiro. O fato gerador cria a obrigação conforme a lei vigente. Em março, a autoridade formaliza o lançamento. Em abril, a empresa paga. São três marcos diferentes: nascimento da obrigação, constituição do crédito e extinção pelo pagamento. Questões trocam essas etapas para criar alternativas erradas.']
    ]
  },
  estadual: {
    overlap:'Legislação tributária estadual aparece nos três; as regras específicas variam por estado',
    sections:[
      ['Mapa dos tributos estaduais', 'ICMS incide sobre circulação de mercadorias e determinadas prestações de transporte interestadual, intermunicipal e comunicação, conforme a Constituição e a legislação aplicável. IPVA recai sobre propriedade de veículos automotores, e ITCMD sobre transmissão causa mortis e doação. Comece cada questão identificando materialidade, contribuinte, ente competente, base de cálculo e regra temporal. Não transporte automaticamente alíquotas ou benefícios de outro estado para o Tocantins.'],
      ['Não cumulatividade do ICMS', 'No esquema didático, o imposto devido nas saídas pode ser compensado com créditos admitidos nas entradas. Se uma saída gera débito de R$ 180 e há crédito regular de R$ 70, o saldo antes de outros ajustes é R$ 110. O cálculo real pode envolver restrições, estornos, substituição tributária, diferencial de alíquotas e regimes específicos. Por isso, use o exemplo apenas para entender a mecânica e consulte o regulamento vigente para resolver casos concretos.'],
      ['Roteiro de leitura da lei tocantinense', 'Abra o portal de legislação da SEFAZ-TO e localize o Código Tributário Estadual, o regulamento do ICMS e atos complementares. Para cada dispositivo, anote: hipótese de incidência, sujeito passivo, local da operação, base de cálculo, alíquota, crédito admitido, obrigação acessória e penalidade. Registre data de consulta e eventual alteração legislativa. Monte uma ficha para ICMS, outra para IPVA e outra para ITCMD. Evite memorizar tabelas sem verificar vigência.'],
      ['Questão modelo', 'Enunciado: “Uma venda de mercadoria no Tocantins pode ser analisada apenas pela alíquota?” Resposta: não. É preciso verificar se a operação é tributada, qual a base, se existe crédito, benefício ou regime próprio, quem deve recolher e quando. Uma alternativa que ignora esses elementos pode estar errada mesmo citando uma alíquota correta.']
    ]
  },
  contabilidade: {
    overlap:'Núcleo central nos três editais',
    sections:[
      ['Patrimônio e partidas dobradas', 'O balanço obedece à equação Ativo = Passivo + Patrimônio Líquido. Ativo representa recursos controlados; passivo, obrigações presentes; patrimônio líquido, participação residual. Débitos e créditos são lados do lançamento, não sinônimos de perda e ganho. Contas do ativo normalmente aumentam a débito; contas do passivo e patrimônio líquido, a crédito. Uma compra de mercadorias a prazo debita Estoques e credita Fornecedores: aumentam ativo e passivo, sem despesa imediata.'],
      ['Regime de competência', 'Receitas e despesas são reconhecidas quando ocorrem os fatos econômicos correspondentes, não necessariamente quando há pagamento. Uma prestação de serviço realizada em dezembro e recebida em janeiro pode gerar receita em dezembro. Para custos, diferencie gasto, investimento, custo de produção e despesa. Mercadoria comprada fica no estoque até a venda; quando vendida, seu valor compõe o custo das mercadorias vendidas.'],
      ['Demonstrações e reconciliação', 'O balanço retrata posição em uma data. A DRE mostra desempenho durante um período. A demonstração dos fluxos de caixa organiza entradas e saídas por atividades operacionais, de investimento e de financiamento. Para responder, pergunte se o evento altera lucro, caixa ou ambos. Depreciação reduz resultado e valor contábil do imobilizado, mas não representa saída de caixa no momento do reconhecimento da despesa.'],
      ['Exemplo resolvido', 'A empresa começa com R$ 1.000 em caixa e capital de R$ 1.000. Compra mercadoria à vista por R$ 300: caixa cai a R$ 700 e estoque sobe a R$ 300; o ativo total permanece R$ 1.000. Vende essa mercadoria por R$ 500 à vista: caixa vai a R$ 1.200, estoque cai a zero, receita é R$ 500 e CMV é R$ 300. O lucro é R$ 200 e o patrimônio líquido final é R$ 1.200.']
    ]
  },
  custos: {
    overlap:'Contabilidade avançada e de custos aparece nos três editais',
    sections:[
      ['Classificação de gastos', 'Custo está ligado à produção; despesa, à venda e administração; investimento gera benefício em períodos futuros. Custos diretos são atribuídos diretamente ao produto, como matéria-prima identificável. Custos indiretos exigem rateio, como energia compartilhada por linhas de produção. Fixo e variável descrevem comportamento em relação ao volume, dentro de uma faixa relevante; direto e indireto descrevem forma de apropriação. Essas classificações são independentes.'],
      ['Margem de contribuição', 'Margem de contribuição unitária = preço de venda − custos e despesas variáveis unitários. Ela representa quanto cada unidade contribui para cobrir gastos fixos e gerar lucro. Com preço de R$ 100 e variáveis de R$ 60, a margem é R$ 40. Se os fixos são R$ 4.000, o ponto de equilíbrio contábil simples é 4.000 ÷ 40 = 100 unidades. A 120 unidades, o resultado estimado é 120 × 40 − 4.000 = R$ 800.'],
      ['Custeio e decisão', 'No custeio por absorção, custos de produção, fixos e variáveis, são apropriados aos produtos segundo critérios adequados. No custeio variável, custos fixos de produção são tratados como gasto do período para análise gerencial. Os métodos podem produzir resultados diferentes quando a quantidade produzida difere da vendida. Em questão, identifique qual método foi pedido antes de calcular estoque e resultado.'],
      ['Treino', 'Se o preço cai para R$ 90 e o gasto variável permanece R$ 60, a margem cai para R$ 30 e o ponto de equilíbrio sobe para aproximadamente 134 unidades, arredondando para cima. O exemplo mostra por que uma redução de preço pode exigir grande crescimento do volume.']
    ]
  },
  auditoria: {
    overlap:'Núcleo central nos três editais',
    sections:[
      ['Planejamento baseado em risco', 'O auditor compreende a entidade, identifica riscos de distorção relevante e define respostas. Materialidade ajuda a julgar quais erros poderiam influenciar decisões dos usuários. Risco maior pede procedimentos mais fortes ou amplos. O plano não é mera lista de documentos; liga risco, objetivo, procedimento e evidência esperada. Se há suspeita de receitas omitidas, comparar apenas valores declarados pela própria empresa pode ser insuficiente.'],
      ['Evidência e procedimentos', 'Inspeção examina registros ou bens; observação acompanha um processo; confirmação externa busca resposta de terceiro; recálculo testa exatidão aritmética; procedimentos analíticos comparam relações plausíveis. Evidência suficiente trata de quantidade; apropriada, de relevância e confiabilidade. Uma nota fiscal isolada pode demonstrar emissão, mas não necessariamente entrega, recebimento ou correta contabilização. Combine fontes quando necessário.'],
      ['Auditoria fiscal', 'Cruze documentos fiscais, escrituração, estoques, bancos e declarações. Diferença entre entradas de mercadorias e registros de estoque pode indicar erro, perda, mudança de classificação ou omissão; não conclua fraude automaticamente. Investigue explicações, materialidade e trilha documental. Um saldo credor anormal de Caixa é sinal de inconsistência: pagamentos registrados superaram recursos contabilizados, o que requer reconciliação.'],
      ['Caso resolvido', 'O estoque inicial é 100 unidades, compras são 80 e vendas registradas são 120; estoque teórico final é 60. A contagem física encontra 45. A diferença de 15 unidades pede investigação de perdas, devoluções, erros de registro ou saídas não documentadas. O cálculo revela uma anomalia; a conclusão depende de evidência adicional.']
    ]
  },
  publica: {
    overlap:'Direito financeiro e finanças públicas aparecem nos três editais',
    sections:[
      ['PPA, LDO e LOA', 'O Plano Plurianual organiza diretrizes, objetivos e metas de médio prazo; a Lei de Diretrizes Orçamentárias orienta a elaboração do orçamento anual; a Lei Orçamentária Anual estima receitas e fixa despesas. A presença de dotação na LOA não significa dinheiro imediato em caixa nem dispensa etapas de execução. Em provas, diferencie planejamento, autorização e execução.'],
      ['Execução da despesa', 'Empenho reserva dotação para obrigação determinada. Liquidação verifica se o credor cumpriu o objeto e qual valor é devido. Pagamento quita a obrigação. Uma nota de empenho sem entrega do bem não autoriza concluir que houve liquidação. Se uma secretaria empenha R$ 10 mil, recebe bens de R$ 8 mil e paga R$ 8 mil, cada fase tem valor e documentação próprios.'],
      ['Responsabilidade fiscal', 'A Lei de Responsabilidade Fiscal trata de planejamento, transparência, equilíbrio e limites para gestão das contas públicas. Receita corrente líquida, despesa com pessoal, dívida e resultados fiscais são conceitos distintos. Examine período de apuração, ente federativo e exceções legais antes de calcular limites. Consulte a norma vigente para percentuais e procedimentos.'],
      ['Treino', 'Classifique: “previsão de prioridades do exercício” remete à LDO; “estimativa anual de receita e autorização de despesa”, à LOA; “programas e objetivos de médio prazo”, ao PPA. Para um bem recebido, pergunte se houve apenas empenho ou também liquidação antes de marcar pagamento.']
    ]
  },
  economia: {
    overlap:'Economia e finanças públicas aparecem nos três editais',
    sections:[
      ['Oferta, demanda e equilíbrio', 'Uma mudança no preço do próprio bem gera movimento ao longo da curva de demanda, mantidos os demais fatores. Alteração de renda, preferências ou preço de bem relacionado desloca a curva. A oferta também pode deslocar por mudança de custos, tecnologia ou tributos. Se a demanda aumenta sem alteração da oferta, o modelo básico prevê preço e quantidade de equilíbrio maiores. Desenhe os eixos antes de responder questões gráficas.'],
      ['Inflação e juros', 'Inflação mede variação de um índice de preços ao longo do tempo; não é o preço absoluto de um único produto. Juros nominais incluem inflação esperada ou ocorrida, enquanto juros reais buscam medir ganho em poder de compra. Para aproximações pequenas, taxa real ≈ nominal − inflação; para cálculo exato, (1 + real) = (1 + nominal)/(1 + inflação). Com 10% nominal e 5% de inflação, a taxa real é cerca de 4,76%, não exatamente 5%.'],
      ['Finanças públicas', 'Política fiscal envolve receitas, gastos e seus efeitos sobre a economia. Déficit ocorre quando determinada medida de despesas supera receitas no período; dívida é estoque acumulado sujeito a outros fatores. Resultado primário exclui despesas financeiras de juros segundo a metodologia aplicável. Sempre verifique o conceito usado pela questão. Tributos também alteram incentivos, distribuição e preços relativos.'],
      ['Questão modelo', 'Se um imposto eleva custos de produção e os demais fatores ficam constantes, a curva de oferta tende a deslocar-se para a esquerda no modelo simples. O novo equilíbrio tende a ter preço maior e quantidade menor. A divisão econômica do ônus entre comprador e vendedor depende das elasticidades, não apenas de quem recolhe formalmente o imposto.']
    ]
  },
  estatistica: {
    overlap:'Estatística e matemática financeira aparecem nos três editais',
    sections:[
      ['Descrição antes da inferência', 'Identifique o tipo da variável: qualitativa, quantitativa discreta ou contínua. Média é soma dividida pelo número de observações; mediana é o valor central da série ordenada; moda é o valor mais frequente. A série 2, 3, 4, 5, 100 tem média 22,8 e mediana 4. O valor extremo puxa a média, mas não altera tanto a mediana. Relate também dispersão e tamanho da amostra.'],
      ['Probabilidade condicional', 'P(A|B) = P(A ∩ B)/P(B), desde que P(B) > 0. A ordem importa: probabilidade de fraude dado um alerta não é igual à probabilidade de alerta dado uma fraude. Exemplo: entre 100 processos alertados, 20 têm irregularidade; P(irregularidade|alerta) = 20%. Não é possível calcular P(alerta|irregularidade) sem saber quantos processos irregulares existem no total.'],
      ['Amostragem e testes', 'Uma amostra grande pode continuar enviesada se foi escolhida de modo inadequado. Amostragem aleatória dá chances conhecidas de seleção; amostra de conveniência não. Em testes de hipótese, o valor-p mede compatibilidade dos dados com o modelo sob a hipótese nula, não a probabilidade de a hipótese ser verdadeira. Erro tipo I é rejeitar uma hipótese nula verdadeira; erro tipo II é não rejeitar uma hipótese nula falsa.'],
      ['Treino', 'Calcule média e mediana de 10, 12, 13, 15 e 50: média 20, mediana 13. Explique por que a mediana representa melhor um valor típico nessa série. Depois escreva em palavras o denominador de cada probabilidade condicional antes de aplicar números.']
    ]
  },
  historia: {
    overlap:'Complementar local; não é interseção dos três editais',
    sections:[
      ['Formação do Tocantins', 'O Tocantins foi criado pela Constituição de 1988 a partir da porção norte de Goiás. Para estudar com profundidade, monte uma linha do tempo: reivindicações de autonomia, aprovação constitucional, instalação do estado e desenvolvimento da capital. Distinga criação legal, instalação administrativa e inauguração de infraestrutura; são acontecimentos diferentes. Consulte fontes oficiais para nomes e datas específicos.'],
      ['Território e economia', 'Localize o estado no mapa do Brasil, suas divisas, rede hidrográfica e principais eixos de transporte. Relacione ocupação territorial, agropecuária, comércio e serviços. Em dados demográficos ou econômicos, anote ano, unidade e fonte. Uma comparação de PIB total entre municípios não equivale a comparação de PIB por habitante.'],
      ['Método de revisão', 'Crie um mapa sem rótulos e preencha capital, estados limítrofes e rios relevantes. Depois consulte uma fonte oficial e corrija. Para fatos históricos, faça cartões com evento de um lado e data/contexto do outro. Evite decorar listas sem entender a sequência causal.']
    ]
  }
};

// Casos autorais para treinar aplicação, além da leitura conceitual e do quiz.
const workedCases = {
  portugues: [
    ['Reescrita sem alterar o sentido', 'Texto: “Apesar da queda nas vendas, a receita tributária aumentou no trimestre.” A primeira informação é uma concessão: a queda levaria o leitor a esperar receita menor, mas ocorreu o contrário. “Embora as vendas tenham caído, a receita tributária aumentou” preserva a relação. “Como as vendas caíram, a receita aumentou” introduz causa e muda o sentido. “A receita aumentou, portanto as vendas caíram” também cria uma conclusão que o texto não autoriza. Em uma questão, risque opções que troquem o valor do conectivo antes de conferir detalhes gramaticais.'],
    ['Crase e regência em contexto', 'Considere “A equipe apresentou o relatório à diretoria e se referiu a processos antigos.” “Apresentar algo a alguém” pede preposição a, e “diretoria” aceita artigo a: surge à. “Referir-se a” também pede a, porém “processos” é masculino plural e não recebe o artigo feminino singular: permanece a. Um teste útil é substituir o feminino por masculino: “ao diretor” indica que havia preposição e artigo; “aos processos” exigiria estrutura e sentido próprios. Evite a regra simplista de colocar crase antes de qualquer palavra feminina.']
  ],
  logica: [
    ['Juros compostos e desconto', 'Um capital de R$ 2.000 cresce 10% no primeiro período e cai 10% no segundo. O saldo intermediário é 2.000 × 1,10 = 2.200. O desconto seguinte incide sobre 2.200: 2.200 × 0,90 = 1.980. O resultado é 1% menor que o capital inicial, pois 1,10 × 0,90 = 0,99. Não some +10% e −10% e conclua zero: as bases são diferentes. A mesma lógica vale para correção de preços, crescimento de arrecadação e comparação de indicadores.'],
    ['Condicional lógica', 'Frase: “Se a declaração foi entregue, então há recibo.” Defina P = declaração entregue e Q = há recibo. A condicional P → Q falha apenas na situação P verdadeira e Q falsa: houve entrega, mas não há recibo. Se a declaração não foi entregue, a frase não informa necessariamente se existe outro recibo. A contrapositiva “Se não há recibo, então a declaração não foi entregue” é logicamente equivalente à original. A conversa “Se há recibo, houve entrega” não é equivalente sem informação adicional.']
  ],
  informatica: [
    ['Conciliação de bases', 'Uma base de notas fiscais tem campos chave, data, valor e contribuinte. A base de pagamentos tem chave, data e valor pago. Antes de cruzá-las, padronize chaves e datas, elimine espaços e valide se uma chave deveria aparecer uma ou várias vezes. Faça uma junção e classifique registros: nota sem pagamento, pagamento sem nota e pares com valores divergentes. Uma diferença não é fraude por si só; pode haver cancelamento, parcelamento, erro de cadastro ou defasagem temporal. Guarde critérios, versão da base e data da extração para que outra pessoa reproduza a análise.'],
    ['Fórmula de planilha', 'Imagine alíquotas na coluna D e bases na coluna C. A fórmula =C2*D2 usa referências relativas e funciona ao copiar para baixo. Se todas as linhas usam uma taxa de referência localizada em H1, use =C2*$H$1. Ao copiar, C2 vira C3, mas $H$1 permanece fixo. Confira células vazias, percentuais armazenados como texto e valores negativos antes de somar. Uma planilha que calcula sem erro de sintaxe ainda pode estar errada por dados ou referências inadequadas.']
  ],
  constitucional: [
    ['Competência tributária e federação', 'Suponha que um estado aprove lei instituindo imposto sobre serviços de qualquer natureza, de competência municipal. A primeira pergunta não é a alíquota nem a finalidade arrecadatória: é se a Constituição atribuiu ao estado a competência para aquele imposto. Em regra, o ISS pertence aos municípios e ao Distrito Federal nos termos constitucionais. Uma lei estadual não muda a repartição de competência. Já o ICMS pertence aos estados e ao Distrito Federal. Em operações complexas, a legislação complementar e a jurisprudência podem definir a incidência aplicável; por isso, o estudo começa pela Constituição e depois desce às normas específicas.'],
    ['Controle concreto e abstrato', 'Uma empresa questiona, em processo próprio, a aplicação de lei tributária que considera incompatível com a Constituição. O juiz pode analisar a questão constitucional incidentalmente ao caso: esse é o cenário típico do controle difuso. Em ação de controle abstrato, discute-se a validade da norma em tese no órgão constitucionalmente competente, sem depender do crédito daquela empresa específica. Em questões, procure expressões como “caso concreto”, “ação própria”, “antes da promulgação” e “lei já vigente”. Elas revelam o tipo de controle.']
  ],
  administrativo: [
    ['Fiscalização e motivação', 'Um fiscal lavra auto por suposta irregularidade. Para avaliar a validade, identifique a norma que atribui competência ao agente, os fatos verificados, a regra aplicada e a forma exigida para o ato. Se a decisão afirma apenas “por interesse público”, sem indicar fatos e fundamento quando a motivação é exigida, o administrado pode ficar sem condições de exercer defesa. O poder de polícia autoriza fiscalização dentro dos limites legais; não confere liberdade para inventar infrações. Separe legalidade do ato, conveniência administrativa e prova dos fatos.'],
    ['Contratação pública', 'Uma repartição precisa de equipamento e alega urgência. A urgência pode ser juridicamente relevante, mas não transforma automaticamente toda compra em contratação direta. O processo precisa demonstrar a hipótese legal aplicável, a necessidade, a escolha do contratado e a justificativa do preço, conforme a lei. Inexigibilidade envolve inviabilidade de competição; dispensa é hipótese legal de contratação sem disputa ainda que a competição possa ser possível. Quando a prova usa as duas palavras como sinônimos, a alternativa costuma estar incorreta.']
  ],
  tributario: [
    ['Linha do tempo do crédito', 'Uma operação ocorreu em 10 de janeiro. Naquele momento, se a hipótese legal se realizou, nasce a obrigação tributária. A autoridade realiza lançamento em 15 de março, constituindo o crédito tributário conforme o procedimento aplicável. O contribuinte apresenta impugnação com efeito de suspensão da exigibilidade, nos termos legais. Após decisão definitiva, paga em julho. A obrigação, a constituição, a suspensão da exigibilidade e a extinção pelo pagamento são etapas diferentes. Uma questão pode pedir qual delas impede cobrança imediata sem extinguir o crédito: a resposta é suspensão, não pagamento.'],
    ['Imunidade, isenção e não incidência', 'Uma imunidade decorre diretamente da Constituição e limita a competência para tributar uma situação protegida. Uma isenção é previsão legal que dispensa o tributo em hipótese compreendida no campo de incidência. Não incidência, em sentido amplo, indica que o fato não se enquadra na hipótese legal de tributação. Para classificar corretamente, pergunte qual é a fonte da proteção e se o fato, sem ela, estaria sujeito ao tributo. Não resolva apenas pela frase “não pagou imposto”, pois o mesmo resultado financeiro pode ter fundamentos jurídicos diferentes.']
  ],
  estadual: [
    ['Apuração didática do ICMS', 'Considere mercadorias adquiridas com crédito admitido de R$ 800 e saídas do período com débito de R$ 1.500. O saldo inicial da apuração é R$ 700 a recolher. Agora suponha que parte da entrada não dá direito a crédito ou que houve benefício com estorno: o saldo muda. Por isso, o passo correto é verificar a natureza das operações, documentos e regras de creditamento antes de subtrair. Substituição tributária e diferencial de alíquotas seguem lógicas específicas. O exemplo ensina a mecânica básica, não determina o valor devido em um caso real.'],
    ['Ficha de legislação local', 'Ao ler uma regra do ICMS do Tocantins, monte uma ficha com oito campos: fato gerador, contribuinte, responsável, base de cálculo, alíquota, crédito, prazo e obrigação acessória. Copie o número do dispositivo e a data de acesso à versão consolidada. Se o dispositivo remete a convênio, anexo ou ato complementar, registre a remissão. Depois resolva um caso simples e marque quais fatos ainda faltam. Essa prática evita decorar alíquotas isoladas e reduz erros causados por normas alteradas.']
  ],
  contabilidade: [
    ['Lançamentos completos', 'A empresa recebe R$ 5.000 dos sócios: débito em Caixa e crédito em Capital Social. Compra estoque por R$ 2.000 a prazo: débito em Estoques e crédito em Fornecedores. Vende metade do estoque por R$ 1.500 à vista: débito em Caixa e crédito em Receita de Vendas; débito em Custo das Mercadorias Vendidas e crédito em Estoques por R$ 1.000. Antes de impostos e outras despesas, o resultado é R$ 500. O caixa final é R$ 6.500, o estoque é R$ 1.000, o passivo é R$ 2.000 e o patrimônio líquido é R$ 5.500. Confira: ativo 7.500 = passivo 2.000 + patrimônio líquido 5.500.'],
    ['Competência versus caixa', 'Uma empresa paga em janeiro R$ 12.000 por seguro que cobre doze meses. O caixa diminui imediatamente. A despesa, pelo regime de competência, é apropriada ao longo da cobertura, R$ 1.000 por mês, se não houver circunstância especial. No pagamento inicial, reconhece-se um ativo de despesa antecipada. Após três meses de cobertura, restam R$ 9.000 nesse ativo e R$ 3.000 foram apropriados como despesa. Questões fiscais podem explorar a confusão entre pagamento, custo, despesa e reconhecimento patrimonial.']
  ],
  custos: [
    ['Custo unitário e volume', 'Uma fábrica tem custo fixo mensal de R$ 12.000 e custo variável de R$ 20 por unidade. Com 1.000 unidades produzidas, o custo total é 12.000 + 20.000 = R$ 32.000, ou R$ 32 por unidade. Com 2.000 unidades, o total é 12.000 + 40.000 = R$ 52.000, ou R$ 26 por unidade. O custo variável unitário permaneceu R$ 20; o custo fixo total permaneceu R$ 12.000; o fixo por unidade caiu pelo aumento do volume. Esse comportamento vale dentro da faixa de atividade em que a premissa de fixidez se mantém.'],
    ['Decisão com margem', 'Preço R$ 80, variável unitário R$ 50 e fixos R$ 9.000 dão margem de R$ 30 e ponto de equilíbrio de 300 unidades. Um pedido adicional de 100 unidades por R$ 65 cada, sem novos fixos e dentro da capacidade, gera margem incremental de R$ 15 por unidade, ou R$ 1.500. Isso não significa que todo desconto seja vantajoso: capacidade, impostos, canibalização de vendas normais e custos adicionais precisam ser considerados. Em prova, destaque os dados relevantes para a decisão incremental.']
  ],
  auditoria: [
    ['Teste de completude de receitas', 'Para testar se todas as vendas foram registradas, partir somente do razão contábil é fraco: uma venda omitida não estará lá. Busque fonte independente ou anterior ao registro, como documentos fiscais, expedição, pedidos ou extratos, e rastreie até a escrituração. Para testar existência de uma receita registrada, o caminho pode ser inverso: parta do registro e procure documento e entrega correspondentes. A direção do teste depende da afirmação examinada. Completude busca omissões; existência busca registros fictícios ou indevidos.'],
    ['Papel de trabalho', 'Uma análise encontra 15 unidades de diferença no estoque. Um papel de trabalho útil registra objetivo do teste, período, fontes, fórmula, resultado, explicações da administração, testes adicionais e conclusão. Apenas anotar “diferença de 15” não demonstra se o auditor considerou perdas, devoluções ou erro de corte. Documentar permite revisão e reexecução. Antes de concluir irregularidade fiscal, reconcilie unidades, preços, datas e documentos e avalie materialidade.']
  ],
  publica: [
    ['Despesa do início ao fim', 'Uma secretaria precisa comprar computadores. A LOA deve conter autorização orçamentária adequada; o gestor planeja a contratação e observa as regras aplicáveis. Após contratar, emite empenho para reservar dotação. Quando os computadores são entregues e conferidos, ocorre a liquidação do valor devido. Depois vem o pagamento. Se o fornecedor entregou apenas parte dos bens, a liquidação deve refletir o objeto efetivamente recebido. A ordem das etapas ajuda a identificar alternativas que confundem autorização orçamentária com quitação financeira.'],
    ['Resultado fiscal', 'Suponha receitas primárias de R$ 100 milhões e despesas primárias de R$ 95 milhões. O resultado primário simplificado é superávit de R$ 5 milhões. Se há despesa de juros de R$ 8 milhões, não conclua que o resultado nominal é automaticamente déficit de R$ 3 milhões sem verificar metodologia e outros componentes. Provas podem apresentar conceitos de caixa, competência, restos a pagar e dívida. Escreva a definição pedida antes de usar números.']
  ],
  economia: [
    ['Tributo e incidência econômica', 'Um imposto por unidade eleva o custo marginal da oferta no modelo básico. A curva de oferta desloca-se para cima ou esquerda. O preço pago pelo consumidor tende a subir, enquanto o valor líquido recebido pelo produtor tende a cair; a quantidade negociada diminui. Quem recolhe o imposto formalmente não determina sozinho quem suporta o ônus econômico. Se a demanda reage pouco ao preço, consumidores tendem a suportar parcela maior. Se reagem muito, produtores absorvem parcela maior. Esse resultado depende das elasticidades e das premissas do modelo.'],
    ['Taxa nominal e real', 'Um investimento rende 12% no ano e a inflação medida é 6%. R$ 100 viram R$ 112, mas uma cesta que custava R$ 100 passa a R$ 106. O poder de compra final equivale a 112/106 = 1,0566 cestas iniciais, ganho real aproximado de 5,66%. Subtrair 12 − 6 = 6 pontos dá apenas aproximação. Questões que pedem taxa real exata exigem dividir fatores, não subtrair taxas.']
  ],
  estatistica: [
    ['Base de risco e falso positivo', 'Em 1.000 declarações, 50 têm irregularidade. Um alerta identifica 40 dessas 50, mas também sinaliza 90 regulares. Entre as 130 alertadas, apenas 40 são irregulares: P(irregularidade|alerta) = 40/130 ≈ 30,8%. Já P(alerta|irregularidade) = 40/50 = 80%. A segunda taxa mede sensibilidade; a primeira responde à pergunta “dado o alerta, qual a chance de irregularidade?”. Confundir as duas leva a conclusões exageradas sobre modelos de seleção fiscal.'],
    ['Média e mediana', 'Cinco autos têm valores 1, 1, 2, 2 e 44 mil reais. A média é 10 mil, mas quatro dos cinco valores estão abaixo de 3 mil. A mediana é 2 mil. Uma comunicação que informe só a média pode dar impressão errada do caso típico. Em auditoria e análise de arrecadação, relate também distribuição, extremos e tamanho da amostra. Se a banca perguntar qual medida resiste mais a valores extremos, escolha a mediana.']
  ],
  historia: [
    ['Leitura de mapa e indicador', 'Ao comparar municípios, primeiro verifique se a tabela mostra população, PIB total ou PIB por habitante. Um município grande pode ter PIB total maior e PIB por habitante menor. Em um mapa, identifique escala, legenda, orientação e período dos dados. Para revisar o Tocantins, localize a capital, as divisas estaduais e as principais bacias. Depois relacione infraestrutura e atividade econômica, mas não trate uma correlação territorial como prova causal sem dados adicionais.'],
    ['Linha do tempo', 'A criação do Tocantins pela Constituição de 1988 é um marco jurídico. A instalação de órgãos e a consolidação da capital são processos posteriores. Faça cartões separados para “movimento de emancipação”, “criação constitucional”, “instalação do estado” e “desenvolvimento de Palmas”. Essa distinção evita que uma questão com duas datas próximas pareça contraditória. Ao estudar qualquer dado local, confira a fonte governamental e a data de atualização.']
  ]
};
